aws_region      = "us-east-1"
role_arn        = "arn:aws:iam::640111764884:role/stsassume-role"
s3_bucket       = "rs-terraform-statefile01"
s3_key          = "terraform-statefile"
dynamodb_table  = "rs-terraform-statetable"
ami_id          = "ami-073e64e4c237c08ad"
instance_type   = "t2.micro"
key_name        = "awskeypair"
